name: DeviceTree Compiler Test Artifact Comparison

on:
  pull_request:
    branches: [ "1.8.0", "dev" ]

permissions: write-all

jobs:
  build_dtc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make dtc
        run: make dtc
      - name: archive dtc
        uses: actions/upload-artifact@v3
        with:
          name: dtc
          path: ./dtc
  
  build_libdtc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make libdtc
        # run: make libdtc
      - name: archive libdtc
     #  uses: actions/upload-artifact@v3
     #  with:
     #    name: libdtc
     #    path: ./libdtc.so
    needs: [build_dtc]

  generate_artifacts__1_7_0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v1.2.1
      with:
        ref: 1.7.0
    - name: build 1.7.0 test artifacts (cache-enabled)
      run: make tests
    - name: cache 1.7.0 test artifacts
      uses: actions/cache@v3
      with:
        name: 1.7.0
        # TODO: for complete safety, use the commit ID of `1.7.0`'s head
        key: 1.7.0
        path: |
          

  generate_artifacts__branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ github.token }}
    - name: make tests
      run: make tests
    needs: [build_dtc]

  compare_artifacts:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ github.token }}
    - name: fetch__1_7_0
      run: |
        echo ""
    - name: fetch__1_8_0
      run: |
        echo ""
    needs: [generate_artifacts__1_7_0, generate_artifacts__branch]
  
    
    
    
